# This workflow automatically labels new issues and adds them to the project board.
name: Add and Label New Issue

# This action runs every time a new issue is opened in this repository.
on:
  issues:
    types: [opened]

# The single job that will be executed.
jobs:
  process-new-issue:
    name: Process New Issue
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      # Step 1: Add the default component label.
      # This step now has the permission it needs to work.
      - name: Add 'infrastructure' label
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['component: infra']
            });

      # Step 2: Add the issue to the project board.
      # This step uses your separate, more powerful PAT.
      - name: Add to project
        uses: actions/add-to-project@v1.0.1
        with:
          # Your Project URL
          project-url: "https://github.com/orgs/PalmariumAI/projects/2"
          
          # Your Fine-grained PAT stored as a repository secret
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}